import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { motion } from "framer-motion";
import {
    FaTwitter,
    FaGithub,
    FaBook,
    FaRegSmileBeam,
    FaHeart,
} from "react-icons/fa";
import { SiZenn } from "react-icons/si";
import { GiHumanEar } from "react-icons/gi";

import { Archivo_Black } from "next/font/google";

const archivoBlack = Archivo_Black({
    weight: "400",
    subsets: ["latin"],
});

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.home}>
                {/* Introduce */}
                <div className={`section ${styles.main}`}>
                    <div>
                        <motion.div {...headTextAnimation}>
                            <h1 className={`${archivoBlack.className} ${styles.name}`}>
                                Aki
                            </h1>
                        </motion.div>
                        <motion.div {...headContentAnimation}>
                            {/* <h2 className={styles.title}>~Nothing impossible!!!~</h2> */}
                            <p className={styles.description}>
                                高卒実務未経験状態からIT企業に就職した、
                                <br />
                                2年目のバックエンドエンジニアです！(21才)
                                <br />
                                関西在住で、PHP, JavaScriptでのWeb開発を行なっております。
                                <br />
                                {/* <strong>&quot;アウトプットこそ最大の学び &quot;</strong>
                                <br /> */}
                                気軽にご連絡ください！👋
                            </p>
                        </motion.div>
                        <motion.div {...headContentAnimation} className={styles.sns}>
                            <motion.div
                                whileHover={{ scale: 1.1 }}
                                whileTap={{ scale: 0.9 }}
                                className={styles.snsItem}
                            >
                                <a href="https://twitter.com/Masa36940064" target="_blank">
                                    <FaTwitter size={"1.6rem"} />
                                </a>
                            </motion.div>
                            <motion.div
                                whileHover={{ scale: 1.1 }}
                                whileTap={{ scale: 0.9 }}
                                className={styles.snsItem}
                            >
                                <a href="http://qiita.com/Masanarea_qiita" target="_blank">
                                    <FaGithub size={"1.6rem"}></FaGithub>
                                </a>
                            </motion.div>
                            <motion.div
                                whileHover={{ scale: 1.1 }}
                                whileTap={{ scale: 0.9 }}
                                className={styles.snsItem}
                            >
                                <a href="https://zenn.dev/masanarea777" target="_blank">
                                    <SiZenn size={"1.6rem"} />
                                </a>
                            </motion.div>
                        </motion.div>
                    </div>
                    <motion.div {...headImageAnimation}>
                        <div className={styles.selfImage}>
                            <img className={styles.selfImage} src="myProfile/aki_image.jpg" />
                        </div>
                    </motion.div>
                </div>
                {/* P */}
                <div className={`section ${styles.personal}`}>
                    <h2 className="sectionTitle">About me</h2>
                    <motion.div
                        variants={container}
                        initial="hidden"
                        animate="show"
                        className={styles.personalInner}
                    >
                        <motion.div variants={item} className={styles.personalCard}>
                            <motion.div
                                whileHover={{ scale: 1.4 }}
                                whileTap={{ scale: 0.9 }}
                                className={styles.personalIcon}
                            >
                                <FaHeart size={"3rem"} />
                            </motion.div>
                            <p>
                                <strong>好奇心が強く、<br />色々チャレンジしています</strong>
                                <br />
                                ツイッター => 最新技術や技術的なアウトプットをしています。<br />
                                個人開発 => Open AI を使用しアプリ『AI コミュニケーター』や、医療脱毛系のネイティブアプリ(作成中)を開発しています。<br />
                                勉強会 => 積極的に参加しています。また、登壇も予定しています。<br />
                                その他、医療脱毛だったり、ファッションだったり、人と話すことだったり、興味が尽きません！
                            </p>
                        </motion.div>
                        <motion.div variants={item} className={styles.personalCard}>
                            <motion.div
                                whileHover={{ scale: 1.4 }}
                                whileTap={{ scale: 0.9 }}
                                className={styles.personalIcon}
                            >
                                <FaRegSmileBeam size={"3rem"} />
                            </motion.div>
                            <p>
                                <strong>行動力が強みです</strong>
                                <br />
                                前職では四国での勤務をしていてかなりアクセスが悪かったのですが、
                                それでも勉強会やその他魅力的なイベントに積極的に参加したいと思っていたため、多い時だと月に3回は東京や関西のイベントに参加させていただいていました。
                                <br />
                                クリスマスに異業種交流会に参加したこともあります！笑
                                <br />
                                今後は主に関西や関東を中心にオンライン・オフライン問わず、イベントに積極的に参加させていただきたいと思っておりますので、
                                面白そうなイベント等何かありましたら、声をかけていただけると泣いて喜びます！😆
                            </p>
                        </motion.div>
                        <motion.div variants={item} className={styles.personalCard}>
                            <motion.div
                                whileHover={{ scale: 1.4 }}
                                whileTap={{ scale: 0.9 }}
                                className={styles.personalIcon}
                            >
                                <FaBook size={"3rem"} />
                            </motion.div>
                            <p>
                                <strong>今後の目標</strong>
                                <br />
                                エンジニア一年目は、特に
                                <br />【 <strong>技術のキャッチアップ</strong>】<br />
                                に力を入れてきました。初めてのフレームワークを使用したり、個人学習では学べなかったノウハウをかなり根を詰めて学習しました。結果的には、最初は保守・運用フェーズしか任せていただけなかったものの一人称で案件の開発を任せていただいたり、上流工程(ER図の作成、機能遷移図、昨日一覧表の作成等)の作業にも携わらせていただく機会を設けてもらいました。
                                <br />
                                <br />
                                今後は、主に
                                <br />
                                <strong>【 外部へのアウトプット</strong> 】<br />
                                を積極的に行っていきたいと考えております。
                                既にクラウドソーシングの受注を行なったり、Qiitaに技術記事を投稿したりしていますが、今後はより積極的にアウトプットしていき
                                勉強会での登壇や非異業種の方との交流を増やしていければと考えております。
                            </p>
                        </motion.div>
                    </motion.div>
                </div>
                {/* S */}
                {/* <div className={`section ${styles.skill}`}>
                    <h2 className="sectionTitle">Skill</h2>
                    <motion.div
                        variants={container}
                        initial="hidden"
                        animate="show"
                        className={styles.skillInner}
                    >
                        <motion.div variants={item} className={styles.skillCard}>
                            <motion.div
                                whileHover={{ scale: 1.4 }}
                                whileTap={{ scale: 1 }}
                                className={styles.skillIcon}
                            >
                                <h4
                                    className={`${archivoBlack.className} ${styles.skillCardTitle}`}
                                >
                                    BACKEND
                                </h4>
                            </motion.div>
                            <p>
                                <strong>■ Ruby</strong>
                                <br />
                                <strong>■ Ruby on Rails</strong>
                                <br />
                                <br />
                                以下で表示しているポートフォリオ
                                <br />
                                &quot;Together&quot;は
                                <br />
                                Ruby on Railsで製作いたしました。
                                <br />
                                今後はJAVAに挑戦していきたい!
                            </p>
                        </motion.div>
                        <motion.div variants={item} className={styles.skillCard}>
                            <motion.div
                                whileHover={{ scale: 1.4 }}
                                whileTap={{ scale: 1 }}
                                className={styles.skillIcon}
                            >
                                <h4
                                    className={`${archivoBlack.className} ${styles.skillCardTitle}`}
                                >
                                    FRONTEND
                                </h4>
                            </motion.div>
                            <p>
                                <strong>■ JavaScript</strong>
                                <br />
                                <strong>■ REACT</strong> -学習中
                                <br />
                                <strong>■ Next.js</strong> -学習中
                                <br />
                                <strong>■ Vue.js</strong> -学習中
                                <br />
                                <strong>■ HTML,CSS</strong>
                                <br />
                                <strong>■ Sass(Scss)</strong>
                                <br />
                                <br />
                                このページはREACTとNext.jsで製作しています。
                                学習に伴い改良を重ねていきます！
                                <br />
                                &quot;Together&quot;のデザインはJavaScriptとScSSを用いました。
                            </p>
                        </motion.div>
                        <motion.div variants={item} className={styles.skillCard}>
                            <motion.div
                                whileHover={{ scale: 1.4 }}
                                whileTap={{ scale: 1 }}
                                className={styles.skillIcon}
                            >
                                <h4
                                    className={`${archivoBlack.className} ${styles.skillCardTitle}`}
                                >
                                    INFRA
                                </h4>
                            </motion.div>
                            <p>
                                <strong>■ AWS</strong>
                                <br />
                                <br />
                                基本的なVPC, EC2, IAM, AMI, S3, RDS...
                                <br />
                                などです。
                                <br />
                                まだまだインフラ部分の知識は疎いので努力します！
                            </p>
                        </motion.div>
                    </motion.div>
                </div> */}
                {/* Slider */}
                <div className={`section ${styles.slider}`}>
                    <div className={styles.sliderInner}>
                        <div className={styles.sliderItem}>
                            <img className={styles.sliderItem} src="/pc.png" />
                        </div>
                        <div className={styles.sliderItem}>
                            <img className={styles.sliderItem} src="/daigaku.jpg" />
                        </div>
                        <div className={styles.sliderItem}>
                            <img className={styles.sliderItem} src="/ww.jpg" />
                        </div>
                        <div className={styles.sliderItem}>
                            <img className={styles.sliderItem} src="/study.jpg" />
                        </div>
                        <div className={styles.sliderItem}>
                            <img className={styles.sliderItem} src="/aws.jpg" />
                        </div>
                        <div className={styles.sliderItem}>
                            <img className={styles.sliderItem} src="/fes.jpg" />
                        </div>
                        <div className={styles.sliderItem}>
                            <img className={styles.sliderItem} src="/dmm.png" />
                        </div>
                        <div className={styles.sliderItem}>
                            <img className={styles.sliderItem} src="/image.jpg" />
                        </div>
                    </div>
                </div>
                {/* Portfolio */}
                <div className={`section ${styles.portfolio}`}>
                    <h2 className="sectionTitle">Portfolio</h2>
                    <div className={styles.portfolioInner}>
                        <div className={styles.portfolioCard}>
                            <img className={styles.portfolioImage} src="/together.gif" />
                            <div className={styles.portfolioContent}>
                                <div className={styles.portfolioHeader}>
                                    <h4 className={styles.portfolioTitle}>
                                        <a href="https://aaa.com/" target="_blank">
                                            AI コミュニケーター
                                        </a>
                                    </h4>
                                    <br />
                                    <motion.div
                                        whileHover={{ scale: 1.1 }}
                                        whileTap={{ scale: 0.9 }}
                                    >
                                        <a
                                            href="https://github.com/aaa"
                                            target="_blank"
                                        >
                                            <FaGithub size={"1.6rem"}></FaGithub>
                                        </a>
                                    </motion.div>
                                </div>
                                <p className={styles.portfolioDescription}>
                                    <strong>
                                        報告・連絡・相談をする際に適当に書いてもいい感じに修正してくれるツール<br />
                                        (自身で使用しています笑)
                                    </strong>
                                    {/* <br />
                                    <strong>
                                        &quot;If You Want To Go Far, Go Together&quot;
                                        (遠くへ行きたいならみんなで行け)
                                    </strong>
                                    <br />
                                    <br /> */}
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </>
    );
}

const headTextAnimation = {
    initial: { x: 100, opacity: 0 },
    animate: { x: 0, opacity: 1 },
    transition: {
        type: "spring",
        damping: 5,
        stiffness: 40,
        restDelta: 0.001,
        duration: 0.3,
    },
};

const headContentAnimation = {
    initial: { y: 100, opacity: 0 },
    animate: { y: 0, opacity: 1 },
    transition: {
        type: "spring",
        damping: 7,
        stiffness: 30,
        restDelta: 0.001,
        duration: 0.6,
        delay: 0.2,
        delayChildren: 0.2,
    },
};

const headImageAnimation = {
    initial: { x: 100, opacity: 0 },
    animate: { x: 0, opacity: 1 },
    transition: {
        type: "spring",
        damping: 5,
        stiffness: 40,
        restDelta: 0.001,
        duration: 0.3,
    },
};

const container = {
    hidden: { opacity: 0 },
    show: {
        opacity: 1,
        transition: {
            delayChildren: 0.5,
        },
    },
};

const item = {
    hidden: { opacity: 0 },
    show: { opacity: 1 },
};